
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$python\
$character"""

[directory]
truncation_length = 5
truncation_symbol = '[...]/'

[python]
detect_files = []
detect_extensions = []


